global using NUnit.Framework;
global using SharpMusic.DllHellP;
global using SharpMusic.DllHellP.Abstract;
global using SharpMusic.DllHellP.LowLevelImpl;
global using SharpMusic.DllHellP.Utils;
global using SharpMusic.DllHellP.Extensions;
global using SharpMusic.DllHellP.Exceptions;
global using FFmpeg.AutoGen;
global using static SharpMusic.DllHellPTests.Constants;
global using static SharpMusic.DllHellP.Utils.FFmpegHelper;
global using static FFmpeg.AutoGen.ffmpeg;
