name: running unit tests
on: [push]
jobs:
  unit-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      libav_osname: linux64
      libav_extname: .tar.xz
      libav_libdir: lib
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache dotnet
        id: cache-dotnet
        uses: actions/cache@v3.2.6
        with:
          path: ~/.dotnet
          key: ${{ runner.os }}-dotnet-setup
      - if: steps.cache-dotnet.outputs.cache-hit != 'true'
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - run: dotnet restore
      - run: dotnet build

      - if: runner.os == 'Windows'
        name: reset variable for windows
        run: |
          echo "libav_osname=win64" >> $Env:GITHUB_ENV
          echo "libav_extname=.zip" >> $Env:GITHUB_ENV
          echo "libav_libdir=bin"   >> $Env:GITHUB_ENV
      - name: download ffmpeg
        id: dl_libav
        uses: vcup/release-downloader@v1.7
        with:
          repository: BtbN/FFmpeg-Builds
          latest: true
          # tag: latest
          fileName: ffmpeg-*-${{ env.libav_osname }}-gpl-shared${{ env.libav_extname }}
      - name: move libav
        run: |
          mkdir tmpdir
          tar -xvf ${{ steps.dl_libav.outputs.downloaded_file_0 }} -C tmpdir
          mv tmpdir/*/${{ env.libav_libdir }}/* tests/SharpMusic.DllHellPTests/bin/Debug/net7.0

      - run: dotnet test --settings coverlet.runsettings
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          directory: coverlet.collected
